variables:
  GIT_SUBMODULE_STRATEGY: recursive
  DOCKER_BUILDKIT: 1
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ''

.imagetag_mr:
  variables:
    IMAGE_TAG: $CI_COMMIT_SHORT_SHA

.imagetag_tag:
  variables:
    IMAGE_TAG: $CI_COMMIT_TAG

stages:
  - build

.build:
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$IMAGE_TAG . --build-arg GITLAB_USERNAME=gitlab-ci-token --build-arg GITLAB_ACCESS_TOKEN=$CI_JOB_TOKEN
    - docker push $CI_REGISTRY_IMAGE:$IMAGE_TAG
  tags:
    - shell

build_mr:
  extends:
    - .imagetag_mr
    - .build
  only:
    - merge_request

build_tag:
  extends:
    - .imagetag_tag
    - .build
  only:
    - tags
